<?php

$apikey = $block->getAPIKey();
$customerSession = $block->getCustomerSession();
$widgetUrl = 'https://assets.gameball.co/widget/js/gameball-init.min.js';

if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getCustomerId();  
    $customer = $customerSession->getCustomer();
    $displayName =  $customer->getName();
    $email =  $customer->getEmail();
    $joinDate = date('Y-m-d', strtotime($customer->getCreatedAt()));
    
    echo "<script>
            window.GbLoadInit = function () {
                GbSdk.init({
                    playerUniqueId: '$customerId',
                    playerAttributes: {
                        displayName: '$displayName',
                        email: '$email',
                        joinDate: '$joinDate'
                    },
                    lang: 'en',
                    magento: true,
                    APIKey: '$apikey'
                });
            };
    </script>";

} else {
    echo "<script>
            window.GbLoadInit = function () {
                GbSdk.init({
                    lang: 'en',
                    APIKey: '$apikey'
                });
            };
    </script>";

}

echo "<script defer src='$widgetUrl'></script>";
